/*
 * SEP6-movies backend
 *
 * Backend part of the project delivered for SEP6 course - Movies platform  Authors of project:  Konrad Piotrowski (280053) Aleksander Stefan Bialik (280027)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
	swagger "studies/SEP6-Backend/swagger/models"
	"studies/SEP6-Backend/util"
)

func UserLoginPost(w http.ResponseWriter, r *http.Request) {

	util.RespondWithJSON(w, r, http.StatusOK, "Dummy response - login", nil)
}

func UserPlaylistAddToFavouritePost(w http.ResponseWriter, r *http.Request) {

	util.RespondWithJSON(w, r, http.StatusOK, "Dummy response - add to favourite", nil)
}

func UserPlaylistGetFavouriteGet(w http.ResponseWriter, r *http.Request) {
	util.RespondWithJSON(w, r, http.StatusOK, "Dummy response - get favourite", nil)
}

func UserPlaylistRemoveFromFavouriteMovieIdDelete(w http.ResponseWriter, r *http.Request) {
	util.RespondWithJSON(w, r, http.StatusOK, "Dummy response - remove from favourite playlist", nil)
}

func UserRegisterPost(w http.ResponseWriter, r *http.Request) {

	var register swagger.Register

	if util.DecodeBodyAsJSON(w, r, &register) {

		util.RespondWithJSON(w, r, http.StatusOK, "Dummy response - register", nil)
	}

}
