/*
 * SEP6-movies backend
 *
 * Backend part of the project delivered for SEP6 course - Movies platform  Authors of project:  Konrad Piotrowski (280053) Aleksander Stefan Bialik (280027)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Person struct {

	Name string `json:"name,omitempty"`

	PlaceOfBirth string `json:"place_of_birth,omitempty"`

	DateOfBirth string `json:"date_of_birth,omitempty"`

	DateOfDeath string `json:"date_of_death,omitempty"`

	Biography string `json:"biography,omitempty"`

	Photo string `json:"photo,omitempty"`

	Gender int32 `json:"gender,omitempty"`

	Department string `json:"department,omitempty"`

	Movies []Movie `json:"movies,omitempty"`
}
