/*
 * SEP6-movies backend
 *
 * Backend part of the project delivered for SEP6 course - Movies platform  Authors of project:  Konrad Piotrowski (280053) Aleksander Stefan Bialik (280027)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Movie struct {
	Id int64 `json:"id,omitempty"`

	PosterPath string `json:"poster_path,omitempty"`

	Title string `json:"title,omitempty"`

	Cast []Person `json:"cast,omitempty"`

	VoteAverage float64 `json:"vote_average,omitempty"`

	VoteCount int32 `json:"vote_count,omitempty"`

	Overview string `json:"overview,omitempty"`

	SimilarMovies []Movie `json:"similar_movies,omitempty"`
}
